import { InteractiveObjectRecord, Rect } from './types';

const size = (w: number, h: number): Rect => ({ x: 0, y: 0, w, h });

export const objectRegistry = {
  'administrator-envelope': {
    id: 'administrator-envelope',
    hotspotId: 'administrator-envelope',
    scene: 'door',
    internalName: 'sobre inicial',
    narrativeState: 'visible',
    visualDescription: 'Sobre claro en el piso, bajo la puerta principal.',
    asset: '/bg-entrance.png',
    rect: { x: 41, y: 69, w: 22, h: 12 },
    shape: 'paper',
    minSize: size(10, 7),
    maxSize: size(26, 16),
    action: 'readEnvelope',
    hover: 'papel bajo la puerta',
    touch: 'El papel raspa el piso.',
    sound: 'paper',
    notebookEntry: 'Piden cuaderno y carpeta.',
    inspection: 'administrator-envelope',
    required: true,
  },
  'apartment-door': {
    id: 'apartment-door',
    hotspotId: 'apartment-door',
    scene: 'door',
    internalName: 'puerta principal',
    narrativeState: 'exit',
    visualDescription: 'Puerta de madera central con cerradura visible.',
    asset: '/bg-entrance.png',
    rect: { x: 25, y: 15, w: 25, h: 50 },
    shape: 'door',
    minSize: size(18, 40),
    maxSize: size(32, 62),
    action: 'openApartmentDoor',
    hover: 'cerradura vieja',
    touch: 'La puerta cede tarde.',
    sound: 'door',
    required: true,
  },
  'family-photo': {
    id: 'family-photo',
    hotspotId: 'family-photo',
    scene: 'hallway',
    internalName: 'foto del aparador',
    narrativeState: 'visible',
    visualDescription: 'Grupo de fotos sobre el aparador izquierdo del pasillo.',
    asset: '/bg-hallway.png',
    rect: { x: 3, y: 50, w: 18, h: 28 },
    shape: 'paper',
    minSize: size(10, 12),
    maxSize: size(24, 32),
    action: 'inspectPhoto',
    hover: 'foto corrida',
    touch: 'El vidrio devuelve la puerta de servicio.',
    sound: 'paper',
    notebookEntry: 'La puerta de servicio estaba abierta.',
    inspection: 'family-photo',
    required: true,
  },
  'to-living': {
    id: 'to-living',
    hotspotId: 'to-living',
    scene: 'hallway',
    internalName: 'entrada al living',
    narrativeState: 'exit',
    visualDescription: 'Abertura grande a la izquierda con sillón visible.',
    asset: '/bg-hallway.png',
    rect: { x: 18, y: 17, w: 17, h: 49 },
    shape: 'door',
    minSize: size(10, 30),
    maxSize: size(24, 62),
    action: 'travelLiving',
    hover: 'living',
    touch: 'El sillón cruje desde adentro.',
    sound: 'door',
    required: true,
  },
  'to-kitchen': {
    id: 'to-kitchen',
    hotspotId: 'to-kitchen',
    scene: 'hallway',
    internalName: 'entrada a cocina',
    narrativeState: 'exit',
    visualDescription: 'Puerta al fondo del pasillo con cocina visible.',
    asset: '/bg-hallway.png',
    rect: { x: 48, y: 20, w: 18, h: 43 },
    shape: 'door',
    minSize: size(10, 28),
    maxSize: size(24, 55),
    action: 'travelKitchen',
    hover: 'cocina',
    touch: 'La pava golpea una vez.',
    sound: 'door',
    required: true,
  },
  'to-bedroom': {
    id: 'to-bedroom',
    hotspotId: 'to-bedroom',
    scene: 'hallway',
    internalName: 'puerta dormitorio',
    narrativeState: 'exit',
    visualDescription: 'Puerta derecha de madera, cerrada a medias.',
    asset: '/bg-hallway.png',
    rect: { x: 73, y: 18, w: 14, h: 56 },
    shape: 'door',
    minSize: size(8, 35),
    maxSize: size(20, 68),
    action: 'travelBedroom',
    hover: 'dormitorio',
    touch: 'La percha golpea adentro.',
    sound: 'door',
    required: true,
  },
  'to-service': {
    id: 'to-service',
    hotspotId: 'to-service',
    scene: 'hallway',
    internalName: 'pasillo de servicio',
    narrativeState: 'exit',
    visualDescription: 'Abertura oscura al extremo derecho.',
    asset: '/bg-hallway.png',
    rect: { x: 88, y: 20, w: 10, h: 60 },
    shape: 'door',
    minSize: size(7, 34),
    maxSize: size(15, 72),
    action: 'travelService',
    hover: 'servicio',
    touch: 'El aire sale más frío.',
    sound: 'door',
    required: true,
  },
  'tv-1986': {
    id: 'tv-1986',
    hotspotId: 'tv-1986',
    scene: 'living',
    internalName: 'televisor',
    narrativeState: 'visible',
    visualDescription: 'Televisor de tubo a la derecha, con antenas.',
    asset: '/bg-living.png',
    rect: { x: 55, y: 37, w: 19, h: 22 },
    shape: 'object',
    minSize: size(12, 12),
    maxSize: size(24, 28),
    action: 'watchTV1986',
    hover: 'televisor',
    touch: 'La estática forma un pasillo.',
    sound: 'radio',
    notebookEntry: 'La señal sabe la casa.',
    required: true,
  },
  'radio-cassette': {
    id: 'radio-cassette',
    hotspotId: 'radio-cassette',
    scene: 'living',
    internalName: 'radio',
    narrativeState: 'visible',
    visualDescription: 'Radio sobre mesa baja derecha, bajo la ventana.',
    asset: '/bg-living.png',
    rect: { x: 75, y: 52, w: 14, h: 15 },
    shape: 'object',
    minSize: size(8, 8),
    maxSize: size(18, 18),
    action: 'tuneRadio',
    hover: 'radio',
    touch: 'La cinta arranca tarde.',
    sound: 'radio',
    notebookEntry: 'La voz no improvisa.',
    required: false,
  },
  'valuation-folder': {
    id: 'valuation-folder',
    hotspotId: 'valuation-folder',
    scene: 'living',
    internalName: 'carpeta tasación living',
    narrativeState: 'state-dependent',
    visualDescription: 'Carpeta abierta sobre la mesa baja del living.',
    asset: '/bg-living.png',
    rect: { x: 28, y: 71, w: 31, h: 17 },
    shape: 'paper',
    minSize: size(18, 10),
    maxSize: size(36, 22),
    action: 'inspectValuation',
    hover: 'carpeta',
    touch: 'La cifra baja sola.',
    alternateState: 'Se vuelve final después del protocolo.',
    sound: 'paper',
    notebookEntry: 'El precio mide cansancio.',
    inspection: 'valuation-folder',
    required: true,
  },
  'living-photo-reflection': {
    id: 'living-photo-reflection',
    hotspotId: 'living-photo-reflection',
    scene: 'living',
    internalName: 'foto reflejada',
    narrativeState: 'visible',
    visualDescription: 'Fotos en mesa izquierda bajo la lámpara.',
    asset: '/bg-living.png',
    rect: { x: 2, y: 46, w: 16, h: 26 },
    shape: 'paper',
    minSize: size(8, 12),
    maxSize: size(20, 30),
    action: 'inspectPhoto',
    hover: 'vidrio de foto',
    touch: 'El reflejo no coincide.',
    sound: 'paper',
    required: false,
  },
  'living-hallway': {
    id: 'living-hallway',
    hotspotId: 'living-hallway',
    scene: 'living',
    internalName: 'salida living pasillo',
    narrativeState: 'exit',
    visualDescription: 'Abertura izquierda que vuelve al pasillo.',
    asset: '/bg-living.png',
    rect: { x: 0, y: 17, w: 17, h: 55 },
    shape: 'door',
    minSize: size(9, 35),
    maxSize: size(22, 65),
    action: 'travelHallway',
    hover: 'pasillo',
    touch: 'La lámpara del pasillo sigue prendida.',
    sound: 'door',
    required: true,
  },
  'living-kitchen': {
    id: 'living-kitchen',
    hotspotId: 'living-kitchen',
    scene: 'living',
    internalName: 'salida living cocina',
    narrativeState: 'exit',
    visualDescription: 'Paso derecho hacia cocina y mesa.',
    asset: '/bg-living.png',
    rect: { x: 89, y: 30, w: 9, h: 44 },
    shape: 'door',
    minSize: size(6, 28),
    maxSize: size(14, 56),
    action: 'travelKitchen',
    hover: 'cocina',
    touch: 'Se oye la pava.',
    sound: 'door',
    required: true,
  },
  'accept-low-price': {
    id: 'accept-low-price',
    hotspotId: 'accept-low-price',
    scene: 'living',
    internalName: 'firma precio bajo',
    narrativeState: 'state-dependent',
    visualDescription: 'Zona izquierda de la carpeta abierta sobre la mesa.',
    asset: '/bg-living.png',
    rect: { x: 31, y: 72, w: 20, h: 13 },
    shape: 'paper',
    minSize: size(12, 8),
    maxSize: size(24, 16),
    action: 'acceptLowPrice',
    hover: 'firma',
    touch: 'La casa se calla.',
    sound: 'pencil',
    required: true,
  },
  'refuse-low-price': {
    id: 'refuse-low-price',
    hotspotId: 'refuse-low-price',
    scene: 'living',
    internalName: 'margen de rechazo',
    narrativeState: 'state-dependent',
    visualDescription: 'Margen derecho de la carpeta abierta sobre la mesa.',
    asset: '/bg-living.png',
    rect: { x: 51, y: 73, w: 14, h: 12 },
    shape: 'paper',
    minSize: size(9, 7),
    maxSize: size(18, 16),
    action: 'refusePrice',
    hover: 'margen',
    touch: 'La birome tiembla.',
    sound: 'pencil',
    required: true,
  },
  'fridge-check': {
    id: 'fridge-check',
    hotspotId: 'fridge-check',
    scene: 'kitchen',
    internalName: 'heladera',
    narrativeState: 'visible',
    visualDescription: 'Heladera grande a la derecha con papel en la puerta.',
    asset: '/bg-kitchen.png',
    rect: { x: 76, y: 33, w: 19, h: 42 },
    shape: 'object',
    minSize: size(12, 28),
    maxSize: size(24, 50),
    action: 'checkFridge',
    hover: 'heladera',
    touch: 'Adentro no coincide nada.',
    sound: 'door',
    notebookEntry: 'No era abandono.',
    required: true,
  },
  'big-pot': {
    id: 'big-pot',
    hotspotId: 'big-pot',
    scene: 'kitchen',
    internalName: 'sopera mesa',
    narrativeState: 'visible',
    visualDescription: 'Sopera baja sobre el mantel, en el extremo inferior izquierdo.',
    asset: '/bg-kitchen.png',
    rect: { x: 2, y: 83, w: 13, h: 11 },
    shape: 'object',
    minSize: size(8, 7),
    maxSize: size(16, 14),
    action: 'inspectPot',
    hover: 'sopera',
    touch: 'La tapa pesa demasiado.',
    sound: 'pot',
    notebookEntry: 'Objeto de apego: sopera.',
    required: false,
  },
  'kitchen-folder': {
    id: 'kitchen-folder',
    hotspotId: 'kitchen-folder',
    scene: 'kitchen',
    internalName: 'carpeta mesa cocina',
    narrativeState: 'visible',
    visualDescription: 'Carpeta cerrada sobre la mesa con mantel rojo.',
    asset: '/bg-kitchen.png',
    rect: { x: 42, y: 77, w: 24, h: 17 },
    shape: 'paper',
    minSize: size(15, 10),
    maxSize: size(30, 22),
    action: 'inspectFolder',
    hover: 'carpeta',
    touch: 'Las fechas no cierran.',
    sound: 'paper',
    notebookEntry: 'La oferta baja ya estaba preparada.',
    inspection: 'kitchen-folder',
    required: true,
  },
  'loose-tile': {
    id: 'loose-tile',
    hotspotId: 'loose-tile',
    scene: 'kitchen',
    internalName: 'azulejo flojo',
    narrativeState: 'state-dependent',
    visualDescription: 'Azulejos rajados sobre mesada, junto a utensilios colgados.',
    asset: '/bg-kitchen.png',
    rect: { x: 30, y: 43, w: 12, h: 13 },
    shape: 'object',
    minSize: size(8, 8),
    maxSize: size(16, 16),
    action: 'loosenTile',
    hover: 'azulejo',
    touch: 'Cede como si esperara.',
    alternateState: 'La libreta aparece detrás después de despegarlo.',
    sound: 'ceramic',
    required: true,
  },
  'blue-notebook': {
    id: 'blue-notebook',
    hotspotId: 'blue-notebook',
    scene: 'kitchen',
    internalName: 'libreta escondida',
    narrativeState: 'revealed',
    visualDescription: 'Objeto oculto detrás del azulejo flojo.',
    asset: '/bg-kitchen.png',
    rect: { x: 32, y: 47, w: 11, h: 10 },
    shape: 'paper',
    minSize: size(7, 7),
    maxSize: size(14, 14),
    action: 'takeNotebook',
    hover: 'tela azul',
    touch: 'Está tibia.',
    sound: 'paper',
    notebookEntry: 'La libreta no explica: conecta.',
    inspection: 'blue-notebook',
    required: true,
  },
  'read-notebook-kitchen': {
    id: 'read-notebook-kitchen',
    hotspotId: 'read-notebook-kitchen',
    scene: 'kitchen',
    internalName: 'libreta en mesa',
    narrativeState: 'state-dependent',
    visualDescription: 'La mesa tiene espacio claro para apoyar la libreta.',
    asset: '/bg-kitchen.png',
    rect: { x: 37, y: 74, w: 22, h: 16 },
    shape: 'paper',
    minSize: size(14, 10),
    maxSize: size(28, 20),
    action: 'readNotebook',
    hover: 'libreta',
    touch: 'Sólo anota una línea.',
    sound: 'paper',
    required: false,
  },
  'kitchen-hallway': {
    id: 'kitchen-hallway',
    hotspotId: 'kitchen-hallway',
    scene: 'kitchen',
    internalName: 'salida cocina pasillo',
    narrativeState: 'exit',
    visualDescription: 'Puerta oscura izquierda de la cocina.',
    asset: '/bg-kitchen.png',
    rect: { x: 0, y: 23, w: 13, h: 50 },
    shape: 'door',
    minSize: size(8, 30),
    maxSize: size(18, 60),
    action: 'travelHallway',
    hover: 'pasillo',
    touch: 'La luz queda atrás.',
    sound: 'door',
    required: true,
  },
  'kitchen-service': {
    id: 'kitchen-service',
    hotspotId: 'kitchen-service',
    scene: 'kitchen',
    internalName: 'salida cocina servicio',
    narrativeState: 'exit',
    visualDescription: 'Puerta izquierda al pasillo de servicio.',
    asset: '/bg-kitchen.png',
    rect: { x: 13, y: 12, w: 13, h: 54 },
    shape: 'door',
    minSize: size(8, 34),
    maxSize: size(18, 64),
    action: 'travelService',
    hover: 'servicio',
    touch: 'El aire huele a humedad.',
    sound: 'door',
    required: true,
  },
  'succession-folder': {
    id: 'succession-folder',
    hotspotId: 'succession-folder',
    scene: 'bedroom',
    internalName: 'carpeta dormitorio',
    narrativeState: 'visible',
    visualDescription: 'Carpeta grande sobre mesa inferior izquierda.',
    asset: '/bg-bedroom.png',
    rect: { x: 2, y: 75, w: 27, h: 15 },
    shape: 'paper',
    minSize: size(16, 9),
    maxSize: size(32, 19),
    action: 'inspectFolder',
    hover: 'carpeta',
    touch: 'Tiene una fecha repetida.',
    sound: 'paper',
    required: false,
  },
  'grandmother-keyring': {
    id: 'grandmother-keyring',
    hotspotId: 'grandmother-keyring',
    scene: 'bedroom',
    internalName: 'llavero',
    narrativeState: 'visible',
    visualDescription: 'Llaves sobre la mesa inferior, al lado de la carpeta.',
    asset: '/bg-bedroom.png',
    rect: { x: 30, y: 81, w: 14, h: 9 },
    shape: 'object',
    minSize: size(8, 5),
    maxSize: size(18, 12),
    action: 'inspectKeyring',
    hover: 'llaves',
    touch: 'Falta la azul.',
    sound: 'ceramic',
    notebookEntry: 'La llave azul no está.',
    inspection: 'grandmother-keyring',
    required: true,
  },
  'bedroom-photo': {
    id: 'bedroom-photo',
    hotspotId: 'bedroom-photo',
    scene: 'bedroom',
    internalName: 'foto de mesa de luz',
    narrativeState: 'visible',
    visualDescription: 'Fotos pequeñas junto a la lámpara de la mesa de luz.',
    asset: '/bg-bedroom.png',
    rect: { x: 56, y: 42, w: 14, h: 17 },
    shape: 'paper',
    minSize: size(8, 9),
    maxSize: size(18, 22),
    action: 'inspectPhoto',
    hover: 'foto',
    touch: 'Aparece una puerta atrás.',
    sound: 'paper',
    required: false,
  },
  'bedroom-hallway': {
    id: 'bedroom-hallway',
    hotspotId: 'bedroom-hallway',
    scene: 'bedroom',
    internalName: 'salida dormitorio pasillo',
    narrativeState: 'exit',
    visualDescription: 'Puerta abierta al pasillo en el fondo izquierdo.',
    asset: '/bg-bedroom.png',
    rect: { x: 8, y: 17, w: 16, h: 52 },
    shape: 'door',
    minSize: size(9, 32),
    maxSize: size(22, 62),
    action: 'travelHallway',
    hover: 'pasillo',
    touch: 'El radiador queda frío.',
    sound: 'door',
    required: true,
  },
  'bedroom-service': {
    id: 'bedroom-service',
    hotspotId: 'bedroom-service',
    scene: 'bedroom',
    internalName: 'salida dormitorio servicio',
    narrativeState: 'exit',
    visualDescription: 'Ventana y borde derecho hacia zona de servicio.',
    asset: '/bg-bedroom.png',
    rect: { x: 89, y: 26, w: 9, h: 48 },
    shape: 'door',
    minSize: size(6, 30),
    maxSize: size(14, 58),
    action: 'travelService',
    hover: 'servicio',
    touch: 'La lluvia golpea más fuerte.',
    sound: 'door',
    required: false,
  },
  'service-plan': {
    id: 'service-plan',
    hotspotId: 'service-plan',
    scene: 'service',
    internalName: 'plano en pared',
    narrativeState: 'visible',
    visualDescription: 'Plano expuesto bajo revoque en pared izquierda.',
    asset: '/bg-service.png',
    rect: { x: 28, y: 31, w: 22, h: 25 },
    shape: 'paper',
    minSize: size(14, 16),
    maxSize: size(28, 32),
    action: 'inspectServicePlan',
    hover: 'plano',
    touch: 'No coincide con el pasillo.',
    sound: 'paper',
    notebookEntry: 'El pasillo no figura.',
    inspection: 'service-plan',
    required: true,
  },
  'behavior-sensor': {
    id: 'behavior-sensor',
    hotspotId: 'behavior-sensor',
    scene: 'service',
    internalName: 'medidor de caño',
    narrativeState: 'state-dependent',
    visualDescription: 'Caja rectangular sobre caños verticales, en el centro derecho.',
    asset: '/bg-service.png',
    rect: { x: 55, y: 29, w: 13, h: 18 },
    shape: 'object',
    minSize: size(8, 10),
    maxSize: size(18, 22),
    action: 'inspectBehaviorProfile',
    hover: 'punto rojo',
    touch: 'Imprime una etiqueta.',
    sound: 'intercom',
    notebookEntry: 'También me miden.',
    inspection: 'behavior-sensor',
    required: true,
  },
  'ledger-plan-overlay': {
    id: 'ledger-plan-overlay',
    hotspotId: 'ledger-plan-overlay',
    scene: 'service',
    internalName: 'zona de superposición',
    narrativeState: 'state-dependent',
    visualDescription: 'Plano de pared con espacio para apoyar la libreta.',
    asset: '/bg-service.png',
    rect: { x: 30, y: 54, w: 21, h: 13 },
    shape: 'paper',
    minSize: size(14, 8),
    maxSize: size(26, 17),
    action: 'overlayLedgerAndPlan',
    hover: 'plano',
    touch: 'Las marcas encajan.',
    sound: 'paper',
    required: true,
  },
  'hidden-panel': {
    id: 'hidden-panel',
    hotspotId: 'hidden-panel',
    scene: 'service',
    internalName: 'panel falso',
    narrativeState: 'state-dependent',
    visualDescription: 'Panel rectangular bajo la rejilla, a la derecha del medidor.',
    asset: '/bg-service.png',
    rect: { x: 60, y: 38, w: 17, h: 34 },
    shape: 'door',
    minSize: size(10, 22),
    maxSize: size(22, 40),
    action: 'openHiddenPanel',
    hover: 'panel',
    touch: 'Se abre hacia adentro.',
    sound: 'wood',
    required: true,
  },
  'service-hidden': {
    id: 'service-hidden',
    hotspotId: 'service-hidden',
    scene: 'service',
    internalName: 'entrada al hueco',
    narrativeState: 'revealed',
    visualDescription: 'Mismo panel falso una vez abierto.',
    asset: '/bg-service.png',
    rect: { x: 60, y: 38, w: 17, h: 34 },
    shape: 'door',
    minSize: size(10, 22),
    maxSize: size(22, 40),
    action: 'travelHidden',
    hover: 'hueco',
    touch: 'Adentro no hay eco.',
    sound: 'door',
    required: true,
  },
  'service-hallway': {
    id: 'service-hallway',
    hotspotId: 'service-hallway',
    scene: 'service',
    internalName: 'salida servicio pasillo',
    narrativeState: 'exit',
    visualDescription: 'Puerta izquierda hacia el pasillo principal.',
    asset: '/bg-service.png',
    rect: { x: 0, y: 8, w: 18, h: 80 },
    shape: 'door',
    minSize: size(10, 50),
    maxSize: size(24, 86),
    action: 'travelHallway',
    hover: 'pasillo',
    touch: 'La alfombra vuelve a aparecer.',
    sound: 'door',
    required: true,
  },
  'service-kitchen': {
    id: 'service-kitchen',
    hotspotId: 'service-kitchen',
    scene: 'service',
    internalName: 'salida servicio cocina',
    narrativeState: 'exit',
    visualDescription: 'Lavadero a la derecha, contiguo a la cocina.',
    asset: '/bg-service.png',
    rect: { x: 80, y: 44, w: 17, h: 36 },
    shape: 'door',
    minSize: size(10, 22),
    maxSize: size(22, 44),
    action: 'travelKitchen',
    hover: 'cocina',
    touch: 'El metal golpea del otro lado.',
    sound: 'door',
    required: true,
  },
  'wall-registry': {
    id: 'wall-registry',
    hotspotId: 'wall-registry',
    scene: 'hidden',
    internalName: 'pared marcada',
    narrativeState: 'visible',
    visualDescription: 'Marcas a lápiz en pared derecha iluminada.',
    asset: '/bg-hidden.png',
    rect: { x: 58, y: 16, w: 23, h: 42 },
    shape: 'paper',
    minSize: size(14, 25),
    maxSize: size(28, 48),
    action: 'readNotebook',
    hover: 'marcas',
    touch: 'Hay una línea nueva.',
    sound: 'paper',
    notebookEntry: 'La pared sabe visitas.',
    required: true,
  },
  'expose-protocol': {
    id: 'expose-protocol',
    hotspotId: 'expose-protocol',
    scene: 'hidden',
    internalName: 'mesa de archivo',
    narrativeState: 'state-dependent',
    visualDescription: 'Mesa baja y carpetas en primer plano del espacio oculto.',
    asset: '/bg-hidden.png',
    rect: { x: 43, y: 66, w: 29, h: 21 },
    shape: 'paper',
    minSize: size(18, 12),
    maxSize: size(34, 26),
    action: 'exposeProtocol',
    hover: 'archivo',
    touch: 'Todo queda junto.',
    sound: 'paper',
    required: true,
  },
  'write-name': {
    id: 'write-name',
    hotspotId: 'write-name',
    scene: 'hidden',
    internalName: 'línea final de pared',
    narrativeState: 'state-dependent',
    visualDescription: 'Zona superior derecha de la pared escrita.',
    asset: '/bg-hidden.png',
    rect: { x: 70, y: 25, w: 16, h: 30 },
    shape: 'paper',
    minSize: size(10, 18),
    maxSize: size(20, 36),
    action: 'writeNameAndHangNotebook',
    hover: 'línea vacía',
    touch: 'El lápiz ya está gastado.',
    sound: 'pencil',
    required: false,
  },
  'hidden-service': {
    id: 'hidden-service',
    hotspotId: 'hidden-service',
    scene: 'hidden',
    internalName: 'salida hueco servicio',
    narrativeState: 'exit',
    visualDescription: 'Marco de puerta iluminado a la izquierda.',
    asset: '/bg-hidden.png',
    rect: { x: 2, y: 10, w: 19, h: 80 },
    shape: 'door',
    minSize: size(10, 52),
    maxSize: size(24, 86),
    action: 'travelService',
    hover: 'salida',
    touch: 'El pasillo vuelve a respirar.',
    sound: 'door',
    required: true,
  },
} as const satisfies Record<string, InteractiveObjectRecord>;

export type RegisteredObjectId = keyof typeof objectRegistry;

export function getObjectRecord(id: string) {
  return objectRegistry[id as RegisteredObjectId];
}

export function sceneObjects(scene: InteractiveObjectRecord['scene']) {
  return Object.values(objectRegistry).filter((object) => object.scene === scene);
}
