import { ActionId, FlagId, Hotspot, Requirement, SceneId, SceneRecord } from './types';

const flag = (flagName: FlagId): Requirement => ({ kind: 'flag', flag: flagName });
const notFlag = (flagName: FlagId): Requirement => ({ kind: 'notFlag', flag: flagName });
const carryNotebook: Requirement = { kind: 'carry', item: 'notebook' };
const priorEnding: Requirement = { kind: 'memoryEndings', count: 1 };

function exit(id: string, label: string, rect: Hotspot['rect'], action: ActionId, exitTo: SceneId): Hotspot {
  return { id, label, verb: 'ir', rect, action, exitTo, layer: 'far', sound: 'door' };
}

export const sceneRegistry: Record<Exclude<SceneId, 'ending'>, SceneRecord> = {
  door: {
    id: 'door',
    aria: 'Palier nocturno de edificio antiguo, con puerta de madera, ascensor de reja, escalera y un sobre bajo la puerta.',
    background: { kind: 'image', src: '/bg-entrance.png', width: 1536, height: 1024 },
    ambient: ['ascensor viejo detenido entre pisos', 'caños con aire', 'un televisor lejano sin palabras claras'],
    hotspots: [
      {
        id: 'administrator-envelope',
        label: 'sobre de la tasadora',
        verb: 'leer',
        rect: { x: 41, y: 69, w: 22, h: 12 },
        action: 'readEnvelope',
        layer: 'near',
        sound: 'paper',
      },
      {
        id: 'apartment-door',
        label: 'puerta de la abuela',
        verb: 'entrar',
        rect: { x: 25, y: 15, w: 28, h: 71 },
        action: 'openApartmentDoor',
        exitTo: 'hallway',
        layer: 'mid',
        sound: 'door',
      },
    ],
  },

  hallway: {
    id: 'hallway',
    aria: 'Pasillo de departamento antiguo con aparador, fotos familiares, puerta al living, cocina al fondo y dormitorios laterales.',
    background: { kind: 'image', src: '/bg-hallway.png', width: 1536, height: 1024 },
    ambient: ['madera que trabaja', 'rueda de valija en la vereda', 'llave girando en otro piso'],
    hotspots: [
      {
        id: 'family-photo',
        label: 'foto intervenida',
        verb: 'mover hacia la luz',
        rect: { x: 3, y: 50, w: 18, h: 28 },
        action: 'inspectPhoto',
        layer: 'near',
        sound: 'paper',
        holdMs: 850,
        gesture: 'hold',
      },
      exit('to-living', 'living comedor', { x: 18, y: 17, w: 17, h: 49 }, 'travelLiving', 'living'),
      exit('to-kitchen', 'cocina', { x: 48, y: 20, w: 18, h: 43 }, 'travelKitchen', 'kitchen'),
      exit('to-bedroom', 'dormitorio del fondo', { x: 73, y: 18, w: 14, h: 56 }, 'travelBedroom', 'bedroom'),
      exit('to-service', 'pasillo de servicio', { x: 88, y: 20, w: 10, h: 60 }, 'travelService', 'service'),
    ],
  },

  living: {
    id: 'living',
    aria: 'Living comedor con sillón gastado, vitrina, televisor antiguo, radio y carpeta de tasación sobre la mesa baja.',
    background: { kind: 'image', src: '/bg-living.png', width: 1536, height: 1024 },
    ambient: ['tapizado cediendo', 'platos que vibran en una vitrina', 'colectivo frenando abajo'],
    hotspots: [
      {
        id: 'tv-1986',
        label: 'televisor de 1986',
        verb: 'encender',
        rect: { x: 55, y: 37, w: 19, h: 22 },
        action: 'watchTV1986',
        layer: 'mid',
        sound: 'radio',
        holdMs: 900,
        gesture: 'hold',
      },
      {
        id: 'radio-cassette',
        label: 'radio con cassette',
        verb: 'sintonizar sosteniendo',
        rect: { x: 75, y: 52, w: 14, h: 15 },
        action: 'tuneRadio',
        layer: 'near',
        sound: 'radio',
        holdMs: 1200,
        gesture: 'hold',
      },
      {
        id: 'valuation-folder',
        label: 'carpeta de tasación',
        verb: 'revisar',
        rect: { x: 28, y: 71, w: 31, h: 17 },
        action: 'inspectValuation',
        layer: 'near',
        sound: 'paper',
        visibleWhen: [flag('truthUnderstood'), flag('behaviorProfileSeen')],
        requirements: [flag('truthUnderstood'), flag('behaviorProfileSeen')],
      },
      {
        id: 'living-photo-reflection',
        label: 'reflejo en el vidrio',
        verb: 'alinear',
        rect: { x: 2, y: 46, w: 16, h: 26 },
        action: 'inspectPhoto',
        layer: 'near',
        sound: 'paper',
        holdMs: 900,
        gesture: 'drag',
      },
      {
        id: 'accept-low-price',
        label: 'tasación baja',
        verb: 'firmar',
        rect: { x: 31, y: 72, w: 20, h: 13 },
        action: 'acceptLowPrice',
        layer: 'near',
        sound: 'pencil',
        visibleWhen: [flag('valuationReady')],
        requirements: [flag('valuationReady')],
        gesture: 'place',
      },
      {
        id: 'refuse-low-price',
        label: 'margen de la carpeta',
        verb: 'rechazar precio',
        rect: { x: 51, y: 73, w: 14, h: 12 },
        action: 'refusePrice',
        layer: 'near',
        sound: 'pencil',
        visibleWhen: [flag('valuationReady')],
        requirements: [flag('valuationReady')],
        holdMs: 1100,
        gesture: 'hold',
      },
      exit('living-hallway', 'pasillo', { x: 0, y: 17, w: 17, h: 55 }, 'travelHallway', 'hallway'),
      exit('living-kitchen', 'cocina', { x: 89, y: 30, w: 9, h: 44 }, 'travelKitchen', 'kitchen'),
    ],
  },

  kitchen: {
    id: 'kitchen',
    aria: 'Cocina vieja con azulejos rajados, heladera sin marca, pava al fuego, mesa con hule y carpeta familiar.',
    background: { kind: 'image', src: '/bg-kitchen.png', width: 1536, height: 1024 },
    ambient: ['heladera a contramano', 'gota en la pileta', 'pava enfriándose de a poco'],
    hotspots: [
      {
        id: 'fridge-check',
        label: 'heladera',
        verb: 'verificar comida',
        rect: { x: 76, y: 33, w: 19, h: 42 },
        action: 'checkFridge',
        layer: 'mid',
        sound: 'door',
      },
      {
        id: 'big-pot',
        label: 'sopera reparada',
        verb: 'levantar tapa',
        rect: { x: 2, y: 83, w: 13, h: 11 },
        action: 'inspectPot',
        layer: 'near',
        sound: 'pot',
      },
      {
        id: 'kitchen-folder',
        label: 'carpeta sobre la mesa',
        verb: 'abrir',
        rect: { x: 42, y: 77, w: 24, h: 17 },
        action: 'inspectFolder',
        layer: 'near',
        sound: 'paper',
      },
      {
        id: 'loose-tile',
        label: 'azulejo flojo',
        verb: 'despegar',
        rect: { x: 30, y: 43, w: 12, h: 13 },
        action: 'loosenTile',
        layer: 'mid',
        sound: 'ceramic',
        holdMs: 1100,
        gesture: 'hold',
        visibleWhen: [flag('folderFound'), notFlag('notebookFound')],
        requirements: [flag('folderFound')],
      },
      {
        id: 'blue-notebook',
        label: 'libreta azul',
        verb: 'tomar',
        rect: { x: 32, y: 47, w: 11, h: 10 },
        action: 'takeNotebook',
        layer: 'near',
        sound: 'paper',
        visibleWhen: [flag('tileLoose'), notFlag('notebookFound')],
        requirements: [flag('tileLoose')],
      },
      {
        id: 'read-notebook-kitchen',
        label: 'libreta azul',
        verb: 'abrir sobre la mesa',
        rect: { x: 37, y: 74, w: 22, h: 16 },
        action: 'readNotebook',
        layer: 'near',
        sound: 'paper',
        visibleWhen: [carryNotebook],
        requirements: [carryNotebook],
      },
      exit('kitchen-hallway', 'pasillo', { x: 0, y: 23, w: 13, h: 50 }, 'travelHallway', 'hallway'),
      exit('kitchen-service', 'pasillo de servicio', { x: 13, y: 12, w: 13, h: 54 }, 'travelService', 'service'),
    ],
  },

  bedroom: {
    id: 'bedroom',
    aria: 'Dormitorio de la abuela con cama de hierro, ropero abierto, cajas, llaves y una carpeta de sucesión.',
    background: { kind: 'image', src: '/bg-bedroom.png', width: 1536, height: 1024 },
    ambient: ['percha golpeando dentro del ropero', 'tela que respira cuando pasa el colectivo', 'radiador frío'],
    hotspots: [
      {
        id: 'succession-folder',
        label: 'carpeta de sucesión',
        verb: 'contrastar fechas',
        rect: { x: 2, y: 75, w: 27, h: 15 },
        action: 'inspectFolder',
        layer: 'near',
        sound: 'paper',
      },
      {
        id: 'grandmother-keyring',
        label: 'llaves de la abuela',
        verb: 'mirar etiquetas',
        rect: { x: 30, y: 81, w: 14, h: 9 },
        action: 'inspectKeyring',
        layer: 'near',
        sound: 'ceramic',
      },
      {
        id: 'bedroom-photo',
        label: 'foto en la cómoda',
        verb: 'acercar a la lámpara',
        rect: { x: 56, y: 42, w: 14, h: 17 },
        action: 'inspectPhoto',
        layer: 'mid',
        sound: 'paper',
        holdMs: 850,
        gesture: 'hold',
      },
      exit('bedroom-hallway', 'pasillo', { x: 8, y: 17, w: 16, h: 52 }, 'travelHallway', 'hallway'),
      exit('bedroom-service', 'pasillo de servicio', { x: 89, y: 26, w: 9, h: 48 }, 'travelService', 'service'),
    ],
  },

  service: {
    id: 'service',
    aria: 'Pasillo de servicio con humedad, caños expuestos, rejilla alta, plano bajo pintura y panel falso.',
    background: { kind: 'image', src: '/bg-service.png', width: 1536, height: 1024 },
    ambient: ['viento por la rejilla', 'ascensor respirando del otro lado', 'agua dentro de la pared'],
    hotspots: [
      {
        id: 'service-plan',
        label: 'plano bajo pintura',
        verb: 'levantar borde',
        rect: { x: 28, y: 31, w: 22, h: 25 },
        action: 'inspectServicePlan',
        layer: 'mid',
        sound: 'paper',
        holdMs: 900,
        gesture: 'hold',
      },
      {
        id: 'behavior-sensor',
        label: 'sensor pegado al caño',
        verb: 'leer parpadeo',
        rect: { x: 56, y: 32, w: 20, h: 19 },
        action: 'inspectBehaviorProfile',
        layer: 'mid',
        sound: 'intercom',
        visibleWhen: [flag('servicePlanSeen')],
        requirements: [flag('servicePlanSeen')],
      },
      {
        id: 'ledger-plan-overlay',
        label: 'libreta y plano',
        verb: 'superponer',
        rect: { x: 30, y: 57, w: 24, h: 14 },
        action: 'overlayLedgerAndPlan',
        layer: 'near',
        sound: 'paper',
        visibleWhen: [carryNotebook, flag('servicePlanSeen')],
        requirements: [carryNotebook, flag('servicePlanSeen')],
        gesture: 'place',
      },
      {
        id: 'hidden-panel',
        label: 'panel falso',
        verb: 'correr',
        rect: { x: 60, y: 38, w: 17, h: 34 },
        action: 'openHiddenPanel',
        layer: 'mid',
        sound: 'wood',
        holdMs: 1200,
        gesture: 'hold',
        visibleWhen: [flag('planOverlayDone'), flag('behaviorProfileSeen')],
        requirements: [flag('planOverlayDone'), flag('behaviorProfileSeen')],
      },
      {
        ...exit('service-hidden', 'hueco de servicio', { x: 60, y: 38, w: 17, h: 34 }, 'travelHidden', 'hidden'),
        visibleWhen: [flag('hiddenPanelOpened')],
        requirements: [flag('hiddenPanelOpened')],
      },
      exit('service-hallway', 'pasillo', { x: 0, y: 8, w: 18, h: 80 }, 'travelHallway', 'hallway'),
      exit('service-kitchen', 'cocina', { x: 80, y: 44, w: 17, h: 36 }, 'travelKitchen', 'kitchen'),
    ],
  },

  hidden: {
    id: 'hidden',
    aria: 'Hueco detrás del pasillo de servicio con estantes angostos, cajas, marcas a lápiz y una abertura hacia el pasillo.',
    background: { kind: 'image', src: '/bg-hidden.png', width: 1536, height: 1024 },
    ambient: ['papel contra papel', 'pared hueca', 'tráfico apagado como debajo de una frazada'],
    hotspots: [
      {
        id: 'wall-registry',
        label: 'pared escrita',
        verb: 'leer despacio',
        rect: { x: 58, y: 16, w: 23, h: 42 },
        action: 'readNotebook',
        layer: 'mid',
        sound: 'paper',
        visibleWhen: [carryNotebook],
        requirements: [carryNotebook],
      },
      {
        id: 'expose-protocol',
        label: 'archivo completo',
        verb: 'preparar denuncia',
        rect: { x: 43, y: 66, w: 29, h: 21 },
        action: 'exposeProtocol',
        layer: 'near',
        sound: 'paper',
        visibleWhen: [carryNotebook, flag('truthUnderstood'), flag('valuationReady')],
        requirements: [carryNotebook, flag('truthUnderstood'), flag('valuationReady')],
        gesture: 'place',
      },
      {
        id: 'write-name',
        label: 'última línea',
        verb: 'firmar y escuchar',
        rect: { x: 70, y: 25, w: 16, h: 30 },
        action: 'writeNameAndHangNotebook',
        layer: 'mid',
        sound: 'pencil',
        visibleWhen: [carryNotebook, flag('truthUnderstood'), priorEnding],
        requirements: [carryNotebook, flag('truthUnderstood'), priorEnding],
        holdMs: 1300,
        gesture: 'hold',
      },
      exit('hidden-service', 'volver al pasillo', { x: 2, y: 10, w: 19, h: 80 }, 'travelService', 'service'),
    ],
  },
};

export function visibleHotspotsForScene(state: { scene: SceneId; flags: Record<string, boolean> | Partial<Record<string, boolean>>; carrying: string | null; memory: { endings: unknown[] } }) {
  if (state.scene === 'ending') return [];
  return sceneRegistry[state.scene].hotspots.filter((hotspot) => requirementsMet(state, hotspot.visibleWhen ?? []));
}

export function requirementsMet(
  state: { flags: Partial<Record<string, boolean>>; carrying: string | null; memory: { endings: unknown[] } },
  requirements: Requirement[],
) {
  return requirements.every((requirement) => {
    if (requirement.kind === 'flag') return Boolean(state.flags[requirement.flag]);
    if (requirement.kind === 'notFlag') return !state.flags[requirement.flag];
    if (requirement.kind === 'carry') return state.carrying === requirement.item;
    if (requirement.kind === 'memoryEndings') return state.memory.endings.length >= requirement.count;
    return false;
  });
}
