import { ActionId, FlagId, Hotspot, Requirement, SceneId, SceneRecord } from './types';

const flag = (flagName: FlagId): Requirement => ({ kind: 'flag', flag: flagName });
const notFlag = (flagName: FlagId): Requirement => ({ kind: 'notFlag', flag: flagName });
const carryNotebook: Requirement = { kind: 'carry', item: 'notebook' };
const priorEnding: Requirement = { kind: 'memoryEndings', count: 1 };

function exit(id: string, label: string, rect: Hotspot['rect'], action: ActionId, exitTo: SceneId): Hotspot {
  return { id, objectId: id, label, verb: 'ir', rect, action, exitTo, layer: 'far', sound: 'door' };
}

export const sceneRegistry: Record<Exclude<SceneId, 'ending'>, SceneRecord> = {
  door: {
    id: 'door',
    aria: 'Palier nocturno de edificio antiguo, con puerta de madera, ascensor de reja, escalera y un sobre bajo la puerta.',
    background: { kind: 'image', src: '/bg-entrance.png', width: 1536, height: 1024 },
    ambient: ['ascensor viejo detenido entre pisos', 'caños con aire', 'televisor lejano'],
    hotspots: [
      {
        id: 'administrator-envelope',
        objectId: 'administrator-envelope',
        label: 'sobre',
        verb: 'leer',
        rect: { x: 41, y: 69, w: 22, h: 12 },
        action: 'readEnvelope',
        layer: 'near',
        sound: 'paper',
      },
      {
        id: 'apartment-door',
        objectId: 'apartment-door',
        label: 'puerta',
        verb: 'entrar',
        rect: { x: 25, y: 15, w: 25, h: 50 },
        action: 'openApartmentDoor',
        exitTo: 'hallway',
        layer: 'mid',
        sound: 'door',
      },
    ],
  },

  hallway: {
    id: 'hallway',
    aria: 'Pasillo con aparador, fotos familiares, puerta al living, cocina al fondo y dormitorios laterales.',
    background: { kind: 'image', src: '/bg-hallway.png', width: 1536, height: 1024 },
    ambient: ['madera que trabaja', 'llave en otro piso', 'pava lejana'],
    hotspots: [
      {
        id: 'family-photo',
        objectId: 'family-photo',
        label: 'foto',
        verb: 'mirar',
        rect: { x: 3, y: 50, w: 18, h: 28 },
        action: 'inspectPhoto',
        layer: 'near',
        sound: 'paper',
        holdMs: 850,
        gesture: 'hold',
      },
      exit('to-living', 'living', { x: 18, y: 17, w: 17, h: 49 }, 'travelLiving', 'living'),
      exit('to-kitchen', 'cocina', { x: 48, y: 20, w: 18, h: 43 }, 'travelKitchen', 'kitchen'),
      exit('to-bedroom', 'dormitorio', { x: 73, y: 18, w: 14, h: 56 }, 'travelBedroom', 'bedroom'),
      exit('to-service', 'servicio', { x: 88, y: 20, w: 10, h: 60 }, 'travelService', 'service'),
    ],
  },

  living: {
    id: 'living',
    aria: 'Living comedor con sillón, vitrina, televisor, radio y carpeta sobre la mesa baja.',
    background: { kind: 'image', src: '/bg-living.png', width: 1536, height: 1024 },
    ambient: ['vidrio de vitrina', 'tránsito bajo la lluvia', 'estática corta'],
    hotspots: [
      {
        id: 'tv-1986',
        objectId: 'tv-1986',
        label: 'televisor',
        verb: 'sintonizar',
        rect: { x: 55, y: 37, w: 19, h: 22 },
        action: 'watchTV1986',
        layer: 'mid',
        sound: 'radio',
        holdMs: 900,
        gesture: 'hold',
      },
      {
        id: 'radio-cassette',
        objectId: 'radio-cassette',
        label: 'radio',
        verb: 'rebobinar',
        rect: { x: 75, y: 52, w: 14, h: 15 },
        action: 'tuneRadio',
        layer: 'near',
        sound: 'radio',
        holdMs: 1200,
        gesture: 'hold',
      },
      {
        id: 'valuation-folder',
        objectId: 'valuation-folder',
        label: 'carpeta',
        verb: 'revisar',
        rect: { x: 28, y: 71, w: 31, h: 17 },
        action: 'inspectValuation',
        layer: 'near',
        sound: 'paper',
        visibleWhen: [flag('truthUnderstood'), flag('behaviorProfileSeen')],
        requirements: [flag('truthUnderstood'), flag('behaviorProfileSeen')],
      },
      {
        id: 'living-photo-reflection',
        objectId: 'living-photo-reflection',
        label: 'vidrio',
        verb: 'inclinar',
        rect: { x: 2, y: 46, w: 16, h: 26 },
        action: 'inspectPhoto',
        layer: 'near',
        sound: 'paper',
        holdMs: 900,
        gesture: 'drag',
      },
      {
        id: 'accept-low-price',
        objectId: 'accept-low-price',
        label: 'firma',
        verb: 'firmar',
        rect: { x: 31, y: 72, w: 20, h: 13 },
        action: 'acceptLowPrice',
        layer: 'near',
        sound: 'pencil',
        visibleWhen: [flag('valuationReady')],
        requirements: [flag('valuationReady')],
        gesture: 'place',
      },
      {
        id: 'refuse-low-price',
        objectId: 'refuse-low-price',
        label: 'margen',
        verb: 'tachar',
        rect: { x: 51, y: 73, w: 14, h: 12 },
        action: 'refusePrice',
        layer: 'near',
        sound: 'pencil',
        visibleWhen: [flag('valuationReady')],
        requirements: [flag('valuationReady')],
      },
      exit('living-hallway', 'pasillo', { x: 0, y: 17, w: 17, h: 55 }, 'travelHallway', 'hallway'),
      exit('living-kitchen', 'cocina', { x: 89, y: 30, w: 9, h: 44 }, 'travelKitchen', 'kitchen'),
    ],
  },

  kitchen: {
    id: 'kitchen',
    aria: 'Cocina con heladera sin marca, pava al fuego, mesa con hule, carpeta y azulejos rajados.',
    background: { kind: 'image', src: '/bg-kitchen.png', width: 1536, height: 1024 },
    ambient: ['motor de heladera', 'metal que se enfría', 'gota seca'],
    hotspots: [
      {
        id: 'fridge-check',
        objectId: 'fridge-check',
        label: 'heladera',
        verb: 'abrir',
        rect: { x: 76, y: 33, w: 19, h: 42 },
        action: 'checkFridge',
        layer: 'mid',
        sound: 'door',
      },
      {
        id: 'big-pot',
        objectId: 'big-pot',
        label: 'sopera',
        verb: 'levantar',
        rect: { x: 2, y: 83, w: 13, h: 11 },
        action: 'inspectPot',
        layer: 'near',
        sound: 'pot',
      },
      {
        id: 'kitchen-folder',
        objectId: 'kitchen-folder',
        label: 'carpeta',
        verb: 'abrir',
        rect: { x: 42, y: 77, w: 24, h: 17 },
        action: 'inspectFolder',
        layer: 'near',
        sound: 'paper',
        visibleWhen: [notFlag('folderFound')],
      },
      {
        id: 'loose-tile',
        objectId: 'loose-tile',
        label: 'azulejo',
        verb: 'despegar',
        rect: { x: 30, y: 43, w: 12, h: 13 },
        action: 'loosenTile',
        layer: 'mid',
        sound: 'ceramic',
        visibleWhen: [flag('folderFound'), notFlag('tileLoose'), notFlag('notebookFound')],
        requirements: [flag('folderFound')],
      },
      {
        id: 'blue-notebook',
        objectId: 'blue-notebook',
        label: 'tela azul',
        verb: 'tomar',
        rect: { x: 32, y: 47, w: 11, h: 10 },
        action: 'takeNotebook',
        layer: 'near',
        sound: 'paper',
        visibleWhen: [flag('tileLoose'), notFlag('notebookFound')],
        requirements: [flag('tileLoose')],
      },
      {
        id: 'read-notebook-kitchen',
        objectId: 'read-notebook-kitchen',
        label: 'libreta',
        verb: 'resumir',
        rect: { x: 37, y: 74, w: 22, h: 16 },
        action: 'readNotebook',
        layer: 'near',
        sound: 'paper',
        visibleWhen: [carryNotebook],
        requirements: [carryNotebook],
      },
      exit('kitchen-hallway', 'pasillo', { x: 0, y: 23, w: 13, h: 50 }, 'travelHallway', 'hallway'),
      exit('kitchen-service', 'servicio', { x: 13, y: 12, w: 13, h: 54 }, 'travelService', 'service'),
    ],
  },

  bedroom: {
    id: 'bedroom',
    aria: 'Dormitorio de la abuela con cama de hierro, ropero abierto, cajas, llaves y carpeta.',
    background: { kind: 'image', src: '/bg-bedroom.png', width: 1536, height: 1024 },
    ambient: ['percha dentro del ropero', 'tela contra madera', 'lluvia en ventana'],
    hotspots: [
      {
        id: 'succession-folder',
        objectId: 'succession-folder',
        label: 'carpeta',
        verb: 'comparar',
        rect: { x: 2, y: 75, w: 27, h: 15 },
        action: 'inspectFolder',
        layer: 'near',
        sound: 'paper',
      },
      {
        id: 'grandmother-keyring',
        objectId: 'grandmother-keyring',
        label: 'llaves',
        verb: 'revisar',
        rect: { x: 30, y: 81, w: 14, h: 9 },
        action: 'inspectKeyring',
        layer: 'near',
        sound: 'ceramic',
      },
      {
        id: 'bedroom-photo',
        objectId: 'bedroom-photo',
        label: 'foto',
        verb: 'iluminar',
        rect: { x: 56, y: 42, w: 14, h: 17 },
        action: 'inspectPhoto',
        layer: 'mid',
        sound: 'paper',
        holdMs: 850,
        gesture: 'hold',
      },
      exit('bedroom-hallway', 'pasillo', { x: 8, y: 17, w: 16, h: 52 }, 'travelHallway', 'hallway'),
      exit('bedroom-service', 'servicio', { x: 89, y: 26, w: 9, h: 48 }, 'travelService', 'service'),
    ],
  },

  service: {
    id: 'service',
    aria: 'Pasillo de servicio con humedad, caños expuestos, rejilla alta, plano bajo pintura y panel falso.',
    background: { kind: 'image', src: '/bg-service.png', width: 1536, height: 1024 },
    ambient: ['tubería hueca', 'rejilla con viento', 'golpes detrás del panel'],
    hotspots: [
      {
        id: 'service-plan',
        objectId: 'service-plan',
        label: 'plano',
        verb: 'levantar',
        rect: { x: 28, y: 31, w: 22, h: 25 },
        action: 'inspectServicePlan',
        layer: 'mid',
        sound: 'paper',
      },
      {
        id: 'behavior-sensor',
        objectId: 'behavior-sensor',
        label: 'punto rojo',
        verb: 'mirar',
        rect: { x: 55, y: 29, w: 13, h: 18 },
        action: 'inspectBehaviorProfile',
        layer: 'mid',
        sound: 'intercom',
        visibleWhen: [flag('servicePlanSeen')],
        requirements: [flag('servicePlanSeen')],
      },
      {
        id: 'ledger-plan-overlay',
        objectId: 'ledger-plan-overlay',
        label: 'plano',
        verb: 'superponer',
        rect: { x: 30, y: 54, w: 21, h: 13 },
        action: 'overlayLedgerAndPlan',
        layer: 'near',
        sound: 'paper',
        visibleWhen: [carryNotebook, flag('servicePlanSeen')],
        requirements: [carryNotebook, flag('servicePlanSeen')],
        gesture: 'place',
      },
      {
        id: 'hidden-panel',
        objectId: 'hidden-panel',
        label: 'panel',
        verb: 'correr',
        rect: { x: 60, y: 38, w: 17, h: 34 },
        action: 'openHiddenPanel',
        layer: 'mid',
        sound: 'wood',
        visibleWhen: [flag('planOverlayDone'), flag('behaviorProfileSeen'), notFlag('hiddenPanelOpened')],
        requirements: [flag('planOverlayDone'), flag('behaviorProfileSeen')],
      },
      {
        ...exit('service-hidden', 'hueco', { x: 60, y: 38, w: 17, h: 34 }, 'travelHidden', 'hidden'),
        visibleWhen: [flag('hiddenPanelOpened')],
        requirements: [flag('hiddenPanelOpened')],
      },
      exit('service-hallway', 'pasillo', { x: 0, y: 8, w: 18, h: 80 }, 'travelHallway', 'hallway'),
      exit('service-kitchen', 'cocina', { x: 80, y: 44, w: 17, h: 36 }, 'travelKitchen', 'kitchen'),
    ],
  },

  hidden: {
    id: 'hidden',
    aria: 'Hueco detrás del pasillo de servicio con estantes, cajas, marcas a lápiz y abertura hacia el pasillo.',
    background: { kind: 'image', src: '/bg-hidden.png', width: 1536, height: 1024 },
    ambient: ['papel contra papel', 'pared hueca', 'tráfico tapado'],
    hotspots: [
      {
        id: 'wall-registry',
        objectId: 'wall-registry',
        label: 'marcas',
        verb: 'comparar',
        rect: { x: 58, y: 16, w: 23, h: 42 },
        action: 'readNotebook',
        layer: 'mid',
        sound: 'paper',
        visibleWhen: [carryNotebook],
        requirements: [carryNotebook],
      },
      {
        id: 'expose-protocol',
        objectId: 'expose-protocol',
        label: 'archivo',
        verb: 'unir pruebas',
        rect: { x: 43, y: 66, w: 29, h: 21 },
        action: 'exposeProtocol',
        layer: 'near',
        sound: 'paper',
        visibleWhen: [carryNotebook, flag('truthUnderstood'), flag('valuationReady')],
        requirements: [carryNotebook, flag('truthUnderstood'), flag('valuationReady')],
        gesture: 'place',
      },
      {
        id: 'write-name',
        objectId: 'write-name',
        label: 'línea vacía',
        verb: 'firmar',
        rect: { x: 70, y: 25, w: 16, h: 30 },
        action: 'writeNameAndHangNotebook',
        layer: 'mid',
        sound: 'pencil',
        visibleWhen: [carryNotebook, flag('truthUnderstood'), priorEnding],
        requirements: [carryNotebook, flag('truthUnderstood'), priorEnding],
        holdMs: 1300,
        gesture: 'hold',
      },
      exit('hidden-service', 'salida', { x: 2, y: 10, w: 19, h: 80 }, 'travelService', 'service'),
    ],
  },
};

export function visibleHotspotsForScene(state: { scene: SceneId; flags: Record<string, boolean> | Partial<Record<string, boolean>>; carrying: string | null; memory: { endings: unknown[] } }) {
  if (state.scene === 'ending') return [];
  return sceneRegistry[state.scene].hotspots.filter((hotspot) => requirementsMet(state, hotspot.visibleWhen ?? []));
}

export function requirementsMet(
  state: { flags: Partial<Record<string, boolean>>; carrying: string | null; memory: { endings: unknown[] } },
  requirements: Requirement[],
) {
  return requirements.every((requirement) => {
    if (requirement.kind === 'flag') return Boolean(state.flags[requirement.flag]);
    if (requirement.kind === 'notFlag') return !state.flags[requirement.flag];
    if (requirement.kind === 'carry') return state.carrying === requirement.item;
    if (requirement.kind === 'memoryEndings') return state.memory.endings.length >= requirement.count;
    return false;
  });
}
